# Generated by Django 2.1 on 2018-09-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('student_class', models.CharField(max_length=3)),
                ('no_kp', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('homeroom', models.CharField(max_length=50)),
            ],
        ),
    ]
