# Generated by Django 2.1 on 2018-09-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0002_auto_20180904_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ic',
            field=models.CharField(max_length=11),
        ),
    ]
