# Generated by Django 2.1 on 2018-09-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0003_auto_20180904_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ic',
            new_name='no_ic',
        ),
    ]
