# Generated by Django 2.1 on 2018-09-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0004_auto_20180904_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='no_ic',
            field=models.CharField(default='021313213', max_length=11),
        ),
    ]
