# Generated by Django 2.1 on 2018-09-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0005_auto_20180904_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='4', max_length=1),
        ),
    ]
