# Generated by Django 2.0.2 on 2018-08-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('TF', 'Teacher Fazilawati'), ('TA', 'Teacher Ar'), ('RR', '3R room')], max_length=2)),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('objective', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher_Fazilawati',
        ),
    ]
