# Generated by Django 2.1 on 2018-09-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0002_auto_20180827_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
